apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    envFrom:
    - configMapRef:
        name: cm1
    # env:
    # - name: DB_HOST
    #   valueFrom:
    #     configMapKeyRef:
    #       name: cm1
    #       key: DB_HOST
    # - name: DB_PASS
    #   valueFrom:
    #     configMapKeyRef:
    #       name: cm1
    #       key: DB_PASS